services:
  backend:
    build: ./
    container_name: Backend
    working_dir: /Backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/Backend
    restart: always
    env_file:
      - Backend/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:12.0
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    restart: on-failure
    env_file:
      - Backend/.env

  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres_admin
    ports:
      - "5000:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: on-failure
    env_file:
      - Backend/.env
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres

#  redis:
#    container_name: redis
#    restart: always
#    image: redis:alpine
#    ports:
#      - "6379:6379"
#
#  celery:
#    container_name: celery
#    restart: always
#    working_dir: /Backend
#    build:
#      context: ./
#    command: celery -A celery worker -l info -c 4
#    environment:
#      - DEBUG=1
#      - CELERY_BROKER=redis://redis:6379/0
#      - CELERY_BACKEND=redis://redis:6379:0
#    depends_on:
#      - redis
#    volumes:
#      - ./Backend/src:/Backend/src

  celery:
    build: ./
    container_name: celery
    command:
#      - celery -A dev-server worker -l info
      - ./run_celery.sh
    volumes:
      - ./Backend:/Backend
    restart: always
    env_file:
      - Backend/.env
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis
      - CELERY_RESULT_BACKEND=redis://redis

  redis:
    image: redis
    container_name: redis
    restart: on-failure
    env_file:
      - Backend/.env
    depends_on:
      - backend
#    ports:
#      - "6379:6379"

  redis-admin:
    image: rediscommander/redis-commander:latest
    container_name: redisadmin
    hostname: redisadmin
    ports:
      - "8092:8081"
    restart: always
    env_file:
      - Backend/.env
    depends_on:
      - redis

  celery-beat:
    container_name: celery_beat
    restart: always
    working_dir: /Backend
    build:
      context: ./
    command: celery -A celery beat -l info
    depends_on:
      - redis
      - celery
    volumes:
      - ./Backend/src:/Backend/src


  flower:
    container_name: flower
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - FLOWER_PORT=8888
    ports:
      - 8888:8888


volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  pgadmin_data: {}
